USE Northwind
GO

CREATE TABLE Currency
(
	Country varchar(100) PRIMARY KEY,
	CurrencyName varchar(50),
	Code char(3),
	Symbol nvarchar(5)
)
GO

INSERT INTO Currency
VALUES ('Afghanistan', 'Afghani', 'AFN', N'؋')
	, ('Albania', 'Lek', 'ALL', N'Lek')
	, ('Argentina', 'Peso', 'ARS', N'$')
	, ('Aruba', 'Guilder', 'AWG', N'ƒ')
	, ('Australia', 'Dollar', 'AUD', N'$')
	, ('Austria', 'Euro', 'EUR', N'€')
	, ('Azerbaijan', 'Manat', 'AZN', N'₼')
	, ('Bahamas', 'Dollar', 'BSD', N'$')
	, ('Barbados', 'Dollar', 'BBD', N'$')
	, ('Belarus', 'Ruble', 'BYR', N'p.')
	, ('Belize', 'Dollar', 'BZD', N'BZ$')
	, ('Bermuda', 'Dollar', 'BMD', N'$')
	, ('Bolivia', 'Boliviano', 'BOB', N'$b')
	, ('Bosnia and Herzegovina', 'Convertible Marka', 'BAM', N'KM')
	, ('Botswana', 'Pula', 'BWP', N'P')
	, ('Bulgaria', 'Lev', 'BGN', N'лв')
	, ('Brazil', 'Real', 'BRL', N'R$')
	, ('Brunei', 'Darussalam Dollar', 'BND', N'$')
	, ('Cambodia', 'Riel', 'KHR', N'៛')
	, ('Canada', 'Dollar', 'CAD', N'$')
	, ('Cayman', 'Dollar', 'KYD', N'$')
	, ('Chile', 'Peso', 'CLP', N'$')
	, ('China', 'Yuan Renminbi', 'CNY', N'¥')
	, ('Colombia', 'Peso', 'COP', N'$')
	, ('Costa Rica', 'Colon', 'CRC', N'₡')
	, ('Croatia', 'Kuna', 'HRK', N'kn')
	, ('Cuba', 'Peso', 'CUP', N'₱')
	, ('Czech Republic', 'Koruna', 'CZK', N'Kč')
	, ('Denmark', 'Krone', 'DKK', N'kr')
	, ('Dominican Republic', 'Peso', 'DOP', N'RD$')
	, ('Egypt', 'Pound', 'EGP', N'£')
	, ('El Salvador', 'Colon', 'SVC', N'$')
	, ('Estonia', 'Kroon', 'EEK', N'kr')
	, ('Euro Member', 'Euro', 'EUR', N'€')
	, ('Falkland Islands', 'Pound', 'FKP', N'£')
	, ('Fiji', 'Dollar', 'FJD', N'$')
	, ('Georgia', 'Lari', 'GEL', N'₾')
	, ('Ghana', 'Cedis', 'GHC', N'¢')
	, ('Gibraltar', 'Pound', 'GIP', N'£')
	, ('Guatemala', 'Quetzal', 'GTQ', N'Q')
	, ('Guernsey', 'Pound', 'GGP', N'£')
	, ('Guyana', 'Dollar', 'GYD', N'$')
	, ('Honduras', 'Lempira', 'HNL', N'L')
	, ('Hong Kong', 'Dollar', 'HKD', N'$')
	, ('Hungary', 'Forint', 'HUF', N'Ft')
	, ('Iceland', 'Krona', 'ISK', N'kr')
	, ('India', 'Rupee', 'INR', N'₹')
	, ('Indonesia', 'Rupiah', 'IDR', N'Rp')
	, ('Iran', 'Rial', 'IRR', N'﷼')
	, ('Isle of Man', 'Pound', 'IMP', N'£')
	, ('Israel', 'Shekel', 'ILS', N'₪')
	, ('Jamaica', 'Dollar', 'JMD', N'J$')
	, ('Japan', 'Yen', 'JPY', N'¥')
	, ('Jersey', 'Pound', 'JEP', N'£')
	, ('Kazakhstan', 'Tenge', 'KZT', N'лв')
	, ('Korea (North)', 'Won', 'KPW', N'₩')
	, ('Korea (South)', 'Won', 'KRW', N'₩')
	, ('Kyrgyzstan', 'Som', 'KGS', N'лв')
	, ('Laos', 'Kip', 'LAK', N'₭')
	, ('Latvia', 'Lat', 'LVL', N'Ls')
	, ('Lebanon', 'Pound', 'LBP', N'£')
	, ('Liberia', 'Dollar', 'LRD', N'$')
	, ('Lithuania', 'Litas', 'LTL', N'L')
	, ('Macedonia', 'Denar', 'MKD', N'ден')
	, ('Malaysia', 'Ringgit', 'MYR', N'RM')
	, ('Mauritius', 'Rupee', 'MUR', N'₨')
	, ('Mexico', 'Peso', 'MXN', N'$')
	, ('Mongolia', 'Tughrik', 'MNT', N'₮')
	, ('Mozambique', 'Metical', 'MZN', N'MT')
	, ('Namibia', 'Dollar', 'NAD', N'$')
	, ('Nepal', 'Rupee', 'NPR', N'₨')
	, ('Netherlands', 'Antilles Guilder', 'ANG', N'ƒ')
	, ('New Zealand', 'Dollar', 'NZD', N'$')
	, ('Nicaragua', 'Cordoba', 'NIO', N'C$')
	, ('Nigeria', 'Naira', 'NGN', N'₦')
	, ('Norway', 'Krone', 'NOK', N'kr')
	, ('Oman', 'Rial', 'OMR', N'﷼')
	, ('Pakistan', 'Rupee', 'PKR', N'₨')
	, ('Panama', 'Balboa', 'PAB', N'B/.')
	, ('Paraguay', 'Guarani', 'PYG', N'Gs')
	, ('Peru', 'Nuevo Sol', 'PEN', N'S/.')
	, ('Philippines', 'Peso', 'PHP', N'₱')
	, ('Poland', 'Zloty', 'PLN', N'zł')
	, ('Qatar', 'Riyal', 'QAR', N'﷼')
	, ('Romania', 'New Leu', 'RON', N'lei')
	, ('Russia', 'Ruble', 'RUB', N'₽')
	, ('Saint Helena', 'Pound', 'SHP', N'£')
	, ('Saudi Arabia', 'Riyal', 'SAR', N'﷼')
	, ('Serbia', 'Dinar', 'RSD', N'Дин.')
	, ('Seychelles', 'Rupee', 'SCR', N'₨')
	, ('Singapore', 'Dollar', 'SGD', N'$')
	, ('Solomon Islands', 'Dollar', 'SBD', N'$')
	, ('Somalia', 'Shilling', 'SOS', N'S')
	, ('South Africa', 'Rand', 'ZAR', N'R')
	, ('Sri Lanka', 'Rupee', 'LKR', N'₨')
	, ('Sweden', 'Krona', 'SEK', N'kr')
	, ('Switzerland', 'Franc', 'CHF', N'CHF')
	, ('Suriname', 'Dollar', 'SRD', N'$')
	, ('Syria', 'Pound', 'SYP', N'£')
	, ('Taiwan', 'New Dollar', 'TWD', N'NT$')
	, ('Thailand', 'Baht', 'THB', N'฿')
	, ('Trinidad and Tobago', 'Dollar', 'TTD', N'TT$')
	, ('Turkey', 'Lira', 'TRL', N'₺')
	, ('Tuvalu', 'Dollar', 'TVD', N'$')
	, ('Ukraine', 'Hryvna', 'UAH', N'₴')
	, ('United Kingdom', 'Pound', 'GBP', N'£')
	, ('United States', 'Dollar', 'USD', N'$')
	, ('Uruguay', 'Peso', 'UYU', N'$U')
	, ('Uzbekistan', 'Som', 'UZS', N'лв')
	, ('Venezuela', 'Bolivar Fuerte', 'VEF', N'Bs')
	, ('Viet Nam', 'Dong', 'VND', N'₫')
	, ('Yemen', 'Rial', 'YER', N'﷼')
	, ('Zimbabwe', 'Dollar', 'ZWD', N'Z$')
GO



